export INSIGHT_NETWORK=livenet
export BITCOIND_USER=Ulysseys
export BITCOIND_PASS=DHxfsJmRcQASypXBHAXjSDBCdHAhH6USQpxgdkm1tR7Y
export BITCOIND_P2P_PORT=15714
export BITCOIND_DATADIR=/home/janko33/.blackcoin
export BITCOIND_PORT=8332 
export NODE_ENV=production
export INSIGHT_PORT=3000
npm start
