export INSIGHT_NETWORK=livenet
export BITCOIND_USER=Ulysseys
export BITCOIND_PASS=H9fsJ6RYQASypXBHAXjSDBCdHAhH6USQp3gd7m1tR7D
export BITCOIND_P2P_PORT=15714
export BITCOIND_DATADIR=/home/rkanadev/.Roma-E-Solidus
export BITCOIND_PORT=8332 
export NODE_ENV=production
export INSIGHT_PORT=3000
npm start
